#basic options
title: Claire O'Connell
author: Hobson Lab 
email: oconneca@mail.uc.edu
twiiter_username: natural_habits
github_username: claireloconnell 

#build settings
mardown: kramdown
remote_theme: jekyll/feeling-responsive
